In [8]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
#    query1 = """
#        SELECT name, guestcost
#        FROM FACILITIES
#        """

    query1 = """
        SELECT Facilities.name,
		SUM(CASE 
        		WHEN Bookings.memid > 0 THEN Bookings.slots*Facilities.membercost
            	ELSE Bookings.slots*Facilities.guestcost
        	END 
            ) AS 'total_revenue'
        FROM Bookings
        INNER JOIN Facilities ON Bookings.facid = Facilities.facid
        GROUP BY Facilities.name
        HAVING total_revenue < 1000.
        ORDER BY total_revenue;
        """    
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Table Tennis', 180)
('Snooker Table', 240)
('Pool Table', 270)

In [10]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
#    query1 = """
#        SELECT name, guestcost
#        FROM FACILITIES
#        """

    query1 = """
    SELECT a.surname, a.firstname, b.firstname, b.surname
    FROM Members a
    JOIN Members b ON a.recommendedby = b.memid
    WHERE a.memid > 0
    ORDER BY a.surname, a.firstname;
        """
    

    
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Bader', 'Florence', 'Ponder', 'Stibbons')
('Baker', 'Anne', 'Ponder', 'Stibbons')
('Baker', 'Timothy', 'Jemima', 'Farrell')
('Boothe', 'Tim', 'Tim', 'Rownam')
('Butters', 'Gerald', 'Darren', 'Smith')
('Coplin', 'Joan', 'Timothy', 'Baker')
('Crumpet', 'Erica', 'Tracy', 'Smith')
('Dare', 'Nancy', 'Janice', 'Joplette')
('Genting', 'Matthew', 'Gerald', 'Butters')
('Hunt', 'John', 'Millicent', 'Purview')
('Jones', 'David', 'Janice', 'Joplette')
('Jones', 'Douglas', 'David', 'Jones')
('Joplette', 'Janice', 'Darren', 'Smith')
('Mackenzie', 'Anna', 'Darren', 'Smith')
('Owen', 'Charles', 'Darren', 'Smith')
('Pinker', 'David', 'Jemima', 'Farrell')
('Purview', 'Millicent', 'Tracy', 'Smith')
('Rumney', 'Henrietta', 'Matthew', 'Genting')
('Sarwin', 'Ramnaresh', 'Florence', 'Bader')
('Smith', 'Jack', 'Darren', 'Smith')
('Stibbons', 'Ponder', 'Burton', 'Tracy')
('Worthington-Smyth', 'Henry', 'Tracy', 'Smith')

In [11]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
#    query1 = """
#        SELECT name, guestcost
#        FROM FACILITIES
#        """

    query1 = """
    SELECT COUNT(DISTINCT Bookings.memid) AS member_count, Facilities.name
    FROM Bookings
    INNER JOIN Facilities ON Bookings.facid = Facilities.facid
    WHERE Bookings.memid > 0
    GROUP BY Facilities.name;
        """
    

    
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(24, 'Badminton Court')
(24, 'Massage Room 1')
(12, 'Massage Room 2')
(27, 'Pool Table')
(22, 'Snooker Table')
(24, 'Squash Court')
(25, 'Table Tennis')
(23, 'Tennis Court 1')
(21, 'Tennis Court 2')